### ISSUE TITLE
Change license (again) to WTFPL or CC0

### ISSUE THREAD

**Issue by dfyx** [voodootikigod/logo.js#112]
As far as I can see, the license was only changed from WTFPL to the more restrictive MIT license because someone didn't like the name WTFPL in #72.

The thing is that the MIT license isn't a very good fit for a logo because of two reasons:

- it references "software" (which isn't too bad, SVGs could be considered software)
- it contains the passage "The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software." meaning that every website, t-shirt or sticker that uses the logo is legally required to include the entire license text which obviously isn't feasible.

I guess nobody intends to enforce the latter rule but either way, the WTFPL or the equivalent [CC0](https://creativecommons.org/publicdomain/zero/1.0/) are a better representation of how the files in this repository are intended to be used.

**Comment by suissa** [comment]
Totally agree, WTFPL is the best.

**The choice has to be the better for community independent of personal opinions.**

**Comment by posva** [comment]
WTFPL is not a legally valid license, you should avoid it at all cost. CC0 (Public domain) would be a better choice to avoid the license inclusion clause

**Comment by strugee** [comment]
> WTFPL is not a legally valid license

[citation needed]? It's on the FSF list: https://www.gnu.org/licenses/license-list.html#WTFPL

**Comment by posva** [comment]
it doesn't protect you legally (it's because of the wording used in WTFPL). It's mentioned in the link you share:

> We recommend the Apache 2.0 license since it protects users from patent treachery.

Cheers

**Comment by strugee** [comment]
Ah, I think we're arguing over semantics. It not protecting against patent stupidity != WTFPL not being legally valid.

**Comment by strugee** [comment]
I'll shut up though since the obvious choice is still CC0 and this isn't really important - my bad for sidetracking the discussion.

**Comment by dfyx** [comment]
This issue has been open for over four years and the repo is pretty much dead so I'll close this.
