### ISSUE TITLE
Wikipedia mods keep removing the logo

### ISSUE THREAD

**Issue by RobertWHurst** [voodootikigod/logo.js#19]
I just tried re-adding it and a mod removed it because it was "totally unofficial".
Is this not the officially preposed logo? Should the logo be on the article? Then again maybe it doesn't belong.

Thoughts?

**Comment by waldyrious** [comment]
For what it's worth, the Wikipedia article [currently features this logo](https://en.wikipedia.org/w/index.php?title=JavaScript&oldid=739230245). Let's see how long it lasts...

**Comment by j-f1** [comment]
Logo is still being removed :(
